#!/usr/bin/python

import sys
import struct
from PyQt4 import QtCore, QtGui, uic, QtDBus, QtSql
import socket


class UI(QtGui.QMainWindow):
  def __init__(self, *args):
    super(UI, self).__init__(*args)

    self.server = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    self.server.connect((sys.argv[1], int(sys.argv[2])))

    uic.loadUi('mainwindow.ui', self)

  def write_color_array(self, r, g, b):
    #sys.stdout.write('a')
    #sys.stdout.flush()
    self.server.sendall('a')
    data = struct.pack('='+'BBB'*240, *[b,g,r]*240)
    self.server.sendall(data)
    #sys.stdout.write(data)
    #sys.stdout.flush()

  @QtCore.pyqtSlot(int)
  def on_horizontalSlider_valueChanged(self, num):
#    sys.stdout.write('r')
#    sys.stdout.flush()
    self.server.sendall('r')
    data = struct.pack('=i', num)
    sys.stderr.write("{} {}\n".format(num, len(data)))
#    sys.stdout.write(data)
    self.server.sendall(data)
#    sys.stdout.flush()
    self.label.setText(str(num))

  @QtCore.pyqtSlot(int)
  def on_horizontalSlider_2_valueChanged(self, num):
    self.label_2.setText(str(num))
    self.write_color_array(int(self.label_2.text()),
      int(self.label_3.text()),
      int(self.label_4.text()))

  @QtCore.pyqtSlot(int)
  def on_horizontalSlider_3_valueChanged(self, num):
    self.label_3.setText(str(num))
    self.write_color_array(int(self.label_2.text()),
      int(self.label_3.text()),
      int(self.label_4.text()))

  @QtCore.pyqtSlot(int)
  def on_horizontalSlider_4_valueChanged(self, num):
    self.label_4.setText(str(num))
    self.write_color_array(int(self.label_2.text()),
      int(self.label_3.text()),
      int(self.label_4.text()))

if __name__ == "__main__":
  app = QtGui.QApplication(sys.argv)

  w = UI()
  w.show()
  w.setVisible(True)

  sys.exit(app.exec_())
